name: Caller

on:
  push:
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    uses: datdo178/github-actions/.github/called.yml
    with:
      branch_name: main
      GAROON_VERSION: 'F23.5'
