name: Caller

on:
  push:
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    uses: datdo178/github-actions/.github/called.yml@main
    with:
      GAROON_VERSION: 'F23.5'
