name: Caller

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    uses: datdo178/github-actions/.github/workflows/called.yml@main
